%% ThermoGuard v0.1 - MATLAB reference model

clear;
clc;
close all;

%% Parameters

T_a = 20;   % Ambient temperature [deg C]
C_e = 100;  % Electronics thermal capacitance [J/K]
C_h = 500;  % Heat sinks thermal capacitance [J/K]
R_eh = 0.5; % Thermal resistance, electronics to heat sink [K/W]
G = 2;      % Cooling conductance heat sink to ambient [W/K]
Q = 20;     % Heat generated by electronics [W]   
Qd = 35;    % Disturbance, eat generated by electronics [W]   

%% Initial temperatures

T_e0 = T_a;  % Electronics temperature [deg C]
T_h0 = T_a;  % Heat sink temperature [deg C]

y0 = [T_e0; T_h0]; 

%% Simulation interval

tspan1 = [0 600];
tspan2 = [600 2000];

%% ODE solver

[t1,y1] = ode45(@(t1,y1) solveDerivatives(t1, y1, T_a, Q, R_eh, G, C_e, C_h), tspan1, y0);

y0 = [y1(end,1);y1(end,2)];
[t2,y2] = ode45(@(t2,y2) solveDerivatives(t2, y2, T_a, Qd, R_eh, G, C_e, C_h), tspan2, y0);

t = [t1;t2(2:end)];
y = [y1;y2(2:end,:)];

%% Extract temperature vectors

Te = y(:,1);
Th = y(:,2);

%% Plotting

plot(t,Te)

hold on

plot(t,Th)

title("Change of Temperature Over Time")
xlabel("time in seconds")
ylabel("temperature in °C")
legend("Temperature of Electronics", "Temperature of Heat sink")
grid
xline(600, '--', 'Disturbance', 'HandleVisibility','off')
hold off

%% Calculate temperatures at steady state 

T_h_ss1 = T_a + Q/G;
T_e_ss1 = T_h_ss1 + Q*R_eh;

T_h_ss2 = T_a + Qd/G;
T_e_ss2 = T_h_ss2 + Qd*R_eh;

%% Solve the thermal equations

function v = solveDerivatives(t, y, T_a, Q, R_eh, G, C_e, C_h)
Q_eh = (y(1) - y(2))/R_eh;  % Heat flow electronics to heat sink
Q_ha = (y(2) - T_a)*G;      % Heat flow heat sink to ambient
dT_e = (Q - Q_eh)/C_e;      
dT_h = (Q_eh - Q_ha)/C_h;
v = [dT_e;dT_h];
end

